T: 3
act: relu
amsgrad: false
batchid: 16
batchimage: 4
batchtest: 32
beta1: 0.9
beta2: 0.999
bnneck: true
config: ''
cpu: false
cutout: false
dampening: 0
data_test: DukeMTMC
data_train: DukeMTMC
datadir: /content/ReIDataset/
decay_type: step_40_70
drop_block: false
epochs: 120
epsilon: 1.0e-08
feat_inference: after
feats: 256
gamma: 0.1
h_ratio: 0.33
height: 384
if_labelsmooth: true
loss: 1*CrossEntropy+1*Triplet
lr: 0.00035
lr_decay: 60
margin: 0.3
model: ResNet50
momentum: 0.9
nGPU: 1
nThread: 4
nesterov: true
num_anchors: 1
num_classes: 702
optimizer: ADAM
parts: 2
pcb_different_lr: true
pool: avg
probability: 0.5
random_erasing: true
reset: false
sampler: true
test_every: 10
w_ratio: 1.0
warmup: linear
weight_decay: 0.0005
width: 128
